
service: api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: ServerlessBot
  region: eu-central-1


functions:
  hello:
    handler: handler.hello
    events:
        - http:
            path: hello-test
            method: GET
            cors: true
